"""
FB Logic Class
Version 0.3

This file is generated by FB Devkit. Should add FB logic here.
"""
import json
import logging
import ssl
import urllib.request


# The parameter input class, all input parameter can get here
class ParamInput:
    def __init__(self, data: dict):
        self.input1 = data.get("input1")
        self.input2 = data.get("input2")


# The parameter output class, all output parameter can set here
class ParamOutput:
    def __init__(self):
        self.output1 = None
        self.status = None


class FunctionBlock():
    def __init__(self,
                 input_data: dict,
                 set_output_callback,
                 update_data_table_callback,
                 update_global_table_callback,
                 get_global_table_callback,
                 **kwargs):
        self.input_data = input_data
        self.set_output_callback = set_output_callback
        self.update_data_table_callback = update_data_table_callback
        self.update_global_table_callback = update_global_table_callback
        self.get_global_table_callback = get_global_table_callback
        self.kwargs = kwargs
        self.param_output = ParamOutput()

    def _coerce_json(self, value):
        if isinstance(value, dict):
            return value
        if isinstance(value, str) and value.strip():
            return json.loads(value)
        return {}

    def _build_default_payload(self):
        return {
            "stage": "wfc_live_debug",
            "selected_directions": [
                "maintenance",
                "quality",
                "energy",
                "flexible_production",
                "workflow_canvas",
            ],
            "context": {
                "maintenance": {
                    "f1_pct": 88.0,
                    "warning_lead_time_hours": 30.0,
                    "root_cause_top3_pct": 92.0,
                    "vibration_rms_mm_s": 7.2,
                    "has_threshold_evidence": True,
                },
                "quality": {
                    "defect_rate_pct": 3.4,
                    "detection_confidence_pct": 93.0,
                    "relative_improvement_pct": 6.0,
                    "has_detector_evidence": True,
                },
                "energy": {
                    "forecast_accuracy_pct": 96.0,
                    "saving_pct": 12.0,
                    "idle_kw": 5.8,
                    "has_meter_baseline": True,
                },
                "production": {
                    "schedule_efficiency_gain_pct": 22.0,
                    "component_reuse_pct": 76.0,
                    "target_sku": "SKU-C500",
                    "has_released_checklist": True,
                    "changeover_required": True,
                },
                "workflow_canvas": {
                    "existing_component_use_pct": 72.0,
                    "new_component_reuse_potential_pct": 80.0,
                    "source": "gongyi_mofang_wfc_live_debug",
                },
            },
        }

    def _build_request(self):
        resource = self._coerce_json(self.param_input.input1)
        payload = self._coerce_json(self.param_input.input2)
        if not payload.get("selected_directions"):
            payload = self._build_default_payload()

        base_url = (
            resource.get("baseUrl")
            or resource.get("agentUrl")
            or "https://quick-cats-study.loca.lt"
        )
        endpoint = base_url.rstrip("/") + "/v1/workflow-canvas/decision"
        return endpoint, payload

    def run(self):
        logging.debug("Function block start")
        try:
            self.param_input = ParamInput(self.input_data)
            endpoint, payload = self._build_request()
            body = json.dumps(payload).encode("utf-8")
            request = urllib.request.Request(
                endpoint,
                data=body,
                headers={
                    "Content-Type": "application/json",
                    "bypass-tunnel-reminder": "1",
                },
                method="POST",
            )
            context = ssl._create_unverified_context()
            with urllib.request.urlopen(request, timeout=15, context=context) as response:
                result = json.loads(response.read().decode("utf-8"))

            logging.info(
                "wearedge_decision_ok=%s latency_ms=%s",
                result.get("ok"),
                result.get("latency_ms"),
            )
            print("wearedge_decision_ok", result.get("ok"), "latency_ms", result.get("latency_ms"))
            self.param_output.output1 = json.dumps(result, ensure_ascii=False)
            self.param_output.status = "Good" if result.get("ok") else "Bad"
        except Exception as e:
            logging.error(f"Function block failed with exception: {e}")
            self.param_output.output1 = json.dumps(
                {"ok": False, "error": str(e)},
                ensure_ascii=False,
            )
            self.param_output.status = "Bad"
        finally:
            self.set_output_callback(self.param_output)

    def on_destroy(self):
        """
        Cleanup resources if needed.
        This function will be called automatically when the FB instance is destroyed by spidr while stop workflow manually.
        """
        logging.debug("Function block on destroy")
