#!/usr/bin/env bash
set -Eeuo pipefail

MODEL_DIR="${MODEL_DIR:-/mnt/nvme/models/gemma4-e2b}"
TEXT_REPO="${TEXT_REPO:-unsloth/gemma-4-E2B-it-GGUF}"
TEXT_GLOB="${TEXT_GLOB:-*Q4_K_S*.gguf}"
MMPROJ_REPO="${MMPROJ_REPO:-$TEXT_REPO}"
MMPROJ_GLOB="${MMPROJ_GLOB:-mmproj-F16.gguf}"

if ! command -v hf >/dev/null 2>&1; then
  echo "The Hugging Face CLI 'hf' was not found. Run scripts/setup_jetson.sh first." >&2
  exit 1
fi

mkdir -p "$MODEL_DIR"

echo "Downloading text model: $TEXT_REPO ($TEXT_GLOB)"
hf download "$TEXT_REPO" --include "$TEXT_GLOB" --local-dir "$MODEL_DIR"

echo "Downloading mmproj: $MMPROJ_REPO ($MMPROJ_GLOB)"
hf download "$MMPROJ_REPO" --include "$MMPROJ_GLOB" --local-dir "$MODEL_DIR"

echo "Writing manifest: $MODEL_DIR/manifest.lock"
{
  echo "# Generated by scripts/download_models.sh"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  mapfile -d '' gguf_files < <(find "$MODEL_DIR" -maxdepth 1 -type f -name "*.gguf" -print0 | sort -z)
  if [[ "${#gguf_files[@]}" -eq 0 ]]; then
    echo "No GGUF files were downloaded." >&2
    exit 1
  fi
  sha256sum "${gguf_files[@]}"
} | tee "$MODEL_DIR/manifest.lock"
